# Table Of Content 
1. What is Python Numpy
2. Indexing Arrays 
3. Slicing Array
4. Operations on an Array
5. Arithmetic Functions in Numpy Concatenation of Array
7. Spliting of Array

## Installation 
`!pip install numpy` <--  _we add the exclamation mark for any shell commands(`!cd srcv/py` )_
## Recommended Import 
`import numpy as np`


In [1]:
# import the numpy package as np 
import numpy as np

In [2]:
# create 2 new lists height and weight
person_height = [2.3,3.4,5.4,4,5]
person_weight = [23,43,54,65,76,78,86]

# create 2 numpy arrays from height and weight 
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [3]:
# print person height array
person_height

array([2.3, 3.4, 5.4, 4. , 5. ])

In [4]:
# print person height array
person_weight

array([23, 43, 54, 65, 76, 78, 86])

### Print type 'person_weight'

In [5]:
print(type(person_weight))

<class 'numpy.ndarray'>


# 2. Indexing Arrays

- Indexing in 1 dimension
- Each element in the array can be accessed by passing the positional index of the element

In [7]:
# Get the 1st element
person_weight[0]

23

In [17]:
# Get the 1st 2th and 4th element

person_weight[[0,1,3]]

array([23, 43, 65])

- Indexing multiple dimensions

In [10]:
my_array = np.array([[100,102,103],[102,304,405],[892,223,445]])
my_array

array([[100, 102, 103],
       [102, 304, 405],
       [892, 223, 445]])

- Get element at 3rd row 2nd column


In [11]:
my_array[2,1]

223

- picking a row or column

In [12]:
# Row 
my_array[1]

array([102, 304, 405])

In [13]:
# Picking 2nd column 
my_array[:,2]

array([103, 405, 445])

# 3. Slicing Array
- Slicing 1 dimensional Array

In [19]:
array1 = np.array([122,233,233,44,5,6,7,4])
array1[0:3]
#start is inclusive and end is excluded.


array([122, 233, 233])

In [20]:
# First 3 elements
array1[:3]

array([122, 233, 233])

In [22]:
#All elements from 2 and beyond
array1[2:]

array([233,  44,   5,   6,   7,   4])

### 2D array Slices

In [25]:
my_array = np.array([[100,102,103,102,103],[102,304,405,102,103],[892,223,445,102,103],[892,223,445,102,103]])
# select all rows except the first
# select 3rd and 4th column
my_array[1:,2:4]

array([[405, 102],
       [445, 102],
       [445, 102]])

# Operations on Array

In [31]:
my_array1 = np.array([120,230,310,410,150])
my_array2 = np.arange(5) # creates an arrage of the 1st 5 numebr


- add two arrays

In [32]:
my_array3 = my_array1 + my_array2
my_array3 

array([120, 231, 312, 413, 154])

- if your arrays are notthe same size i you will get an error.

In [33]:
# get square of each element 
my_array**2

array([[ 10000,  10404,  10609,  10404,  10609],
       [ 10404,  92416, 164025,  10404,  10609],
       [795664,  49729, 198025,  10404,  10609],
       [795664,  49729, 198025,  10404,  10609]], dtype=int32)

In [34]:
# Multiply elements by 4
my_array*4

array([[ 400,  408,  412,  408,  412],
       [ 408, 1216, 1620,  408,  412],
       [3568,  892, 1780,  408,  412],
       [3568,  892, 1780,  408,  412]])

- Using Numpy comparison expressions.

In [35]:
my_array1 

array([120, 230, 310, 410, 150])

In [40]:
new_arr = my_array1 >= 150
new_arr

array([False,  True,  True,  True,  True])

- pass the above boolean into the array to get the values that satify the condition.

In [41]:
my_array1[new_arr]

array([230, 310, 410, 150])

### Arithmetic Functions in Numpy

In [43]:
array2=np.array([1,3,5,2,4,6])
# add
array2.sum()


21

In [44]:
# Get minimum
array2.min()

1

In [45]:
# get cube of elements
np.power(array2 ,3)

array([  1,  27, 125,   8,  64, 216], dtype=int32)

### Array Concatenation

In [48]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
np.concatenate([a , b])



array([0, 1, 2, 5, 5, 5])

- Concatenate 2D

In [50]:
my_arr = np.array([[1,2,3],[2,3,4]])
# concatenate along the  axis = 0 to add as rows
np.concatenate([my_arr, my_arr])

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [51]:
# To add as columns
np.concatenate([my_arr, my_arr],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4]])

- TO CONCATENATE arrays of differant dimensts make sure the axes match.

- 7. Splitting an Array

In [53]:
array_x = np.arange(8)
# Split array into subarrays (array_to_split,no_of_sub_arrays)
np.split(array_x,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [56]:
# Split 1D array at positions indicated
# Split occurs at 1st and 3rd index
np.split(array_x,[1,3])

[array([0]), array([1, 2]), array([3, 4, 5, 6, 7])]

- `array_split()` It is used to split the array into sub-arrays. 
It takes the integer N as the input fir the number of splits,even if 'N' does not divide the array into subarrays of equal length.