# Table Of Content 
1. What is Python Numpy
2. Indexing Arrays 
3. Slicing Array
4. Operations on an Array
5. Arithmetic Functions in Numpy Concatenation of Array
7. Spliting of Array

## Installation 
`!pip install numpy` <--  _we add the exclamation mark for any shell commands(`!cd srcv/py` )_
## Recommended Import 
`import numpy as np`


In [1]:
# import the numpy package as np 
import numpy as np

In [2]:
# create 2 new lists height and weight
person_height = [2.3,3.4,5.4,4,5]
person_weight = [23,43,54,65,76,78,86]

# create 2 numpy arrays from height and weight 
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [3]:
# print person height array
person_height

array([2.3, 3.4, 5.4, 4. , 5. ])

In [4]:
# print person height array
person_weight

array([23, 43, 54, 65, 76, 78, 86])

### Print type 'person_weight'

In [5]:
print(type(person_weight))

<class 'numpy.ndarray'>


# 2. Indexing Arrays

- Indexing in 1 dimension
- Each element in the array can be accessed by passing the positional index of the element

In [7]:
# Get the 1st element
person_weight[0]

23

In [17]:
# Get the 1st 2th and 4th element

person_weight[[0,1,3]]

array([23, 43, 65])

- Indexing multiple dimensions

In [10]:
my_array = np.array([[100,102,103],[102,304,405],[892,223,445]])
my_array

array([[100, 102, 103],
       [102, 304, 405],
       [892, 223, 445]])

- Get element at 3rd row 2nd column


In [11]:
my_array[2,1]

223

- picking a row or column

In [12]:
# Row 
my_array[1]

array([102, 304, 405])

In [13]:
# Picking 2nd column 
my_array[:,2]

array([103, 405, 445])

# 3. Slicing Array
- Slicing 1 dimensional Array

In [19]:
array1 = np.array([122,233,233,44,5,6,7,4])
array1[0:3]
#start is inclusive and end is excluded.


array([122, 233, 233])

In [20]:
# First 3 elements
array1[:3]

array([122, 233, 233])

In [22]:
#All elements from 2 and beyond
array1[2:]

array([233,  44,   5,   6,   7,   4])

### 2D array Slices

In [25]:
my_array = np.array([[100,102,103,102,103],[102,304,405,102,103],[892,223,445,102,103],[892,223,445,102,103]])
# select all rows except the first
# select 3rd and 4th column
my_array[1:,2:4]

array([[405, 102],
       [445, 102],
       [445, 102]])